Introduction
YetAnotherSpieskowcy/Carcassonne-Documentation pull request #3
Opened 2024-12-12 11:54 UTC by BognaLew

2024-12-12 12:14 UTC, bstrzelecki approved these changes

2024-12-16 05:03 UTC, Jackenmen requested changes
The introduction text seems fine but I do have some comments on the bibliography.

2024-12-16 05:03 UTC, Jackenmen commented on main.tex
> +\usepackage[backend=biber, style=numeric, bibstyle=ieee,
The configured bibliography style seems inconsistent with the one used in the journal's template where:
- commas seem to be preferred over dots
- titles are not quoted
- the bibliography title is different (should be "References" but is "Literature")

There may also be some discrepancies in formatting - there's weird text justification going on on URLs:
![image](https://github.com/user-attachments/assets/0cd3c99c-c8f1-416e-9cca-759e9c001864)

2024-12-31 03:15 UTC, Jackenmen requested changes
Suggested changes made in the preliminary report that aren't present here.

2024-12-31 03:15 UTC, Jackenmen commented on sections/introduction.tex
> +In October 2015 the world heard about a computer program named AlphaGo that
```suggestion
In 2016 the world heard about a computer program named AlphaGo that in October 2015
```

2024-12-31 03:15 UTC, Jackenmen commented on sections/introduction.tex
> +project attempts to answer this question by preparing an agent for the Carcassonne game
```suggestion
project attempts to answer this question by preparing an agent for the \textit{Carcassonne} game 
```

2024-12-31 03:15 UTC, Jackenmen commented on sections/introduction.tex
> +concentrates on discribing the structure of the game agent and neural network input and
```suggestion
concentrates on describing the structure of the game agent and neural network input and
```

2024-12-31 03:15 UTC, Jackenmen commented on sections/introduction.tex
> +work. The section `Game engine architecture' presents an architecture of the
```suggestion
The following sections present the achieved goals.
The section `Game engine architecture' presents the architecture of the
```

2025-01-06 13:24 UTC, merged